server:
  port: 80
spring:
    application:
      name: cloud-comsumer-order #让监控的数据收集到zipkin上地址如下http://localhost:9411
    zipkin:
      base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1 #采样率值介于0到1之间，1则表示全部采集
eureka:
  client:
   #在微服务提供者一边，提供者需要注册到eureka server,所以作为eureka client需要注册到这eureka设置为ture
    register-with-eureka: true
    #是否需要从eureka server抓取已有注册信息，默认为true,单节点无所谓，集群必须设置为true才能配置ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001//eureka/ #单机版
      defaultZone: http://eureka7001.com:7001//eureka/,http://eureka7002.com:7002/eureka/ #集群版