server:
  port: 9003
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848        #nacos服务地址
management: #监控端点
  endpoints:
    web:
      exposure:
        include: "*"
