server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
spring:
  application:
    name: cloud-consumer-openfeign-hystrix-order
feign:
  hystrix:
    enabled: true  #在消费者 openFeign中开启hystrix 服务降级
ribbon:
  #建立连接所有时间，网络正常情况下，两端所用的时间
  ReadTimeout: 5000
  #建立连接后从提供者微服务读取到资源所用时间
  ConnectTimeout: 5000