server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #注册到nacos注册中心8848
    sentinel:
      transport:
       #sentinel dashboard 服务地址,让微服务8401和sentinel发生关系，也就是让sentine8080监控8401
        dashboard: localhost:8080
        port: 8719   #默认8719端口，假如sentinel默认端口被占用会自动从8719开始依次+1扫描,直到未找到占用的端口
      datasource:   #sentinel 持久化到nacos
        ds1:     #ds1 数据源
          nacos:
            server-addr: localhost:8848  #nacos地址
            dataId: ${spring.application.name}  #应用程序名
            groupId: DEFAULT_GROUP  #默认分组
            data_type: json   #json格式
            rule_type: flow

management:
  endpoints:
    web:
      exposure:
        include: "*"
